- name: block IP address
  hosts: cisco
  connection: httpapi

  tasks:
    - include_role:
        name: acl_manager
        tasks_from: block_ip
      vars:
        source_ip: 192.168.56.103
        destination_ip: 192.168.56.104
        ansible_network_os: checkpoint
